<a href="https://colab.research.google.com/github/Ibilis37/DeepLearning/blob/main/ML_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import random
import copy
import random

 Создаyние модели (без использования готовых решений) простейшего перцептрона, которая будет выполнять функцию логического "ИЛИ".



In [ ]:
dataset = list()
dataset.append(([0, 0],0))
dataset.append(([0, 1],1))
dataset.append(([1, 0],1))
dataset.append(([1, 1],1))

noise_dataset = list()
for i in range(10000):
  noise_dataset.append(copy.deepcopy(random.choice(dataset)))
  for j in range(2):
    noise_dataset[i][0][j] += (random.randint(-45, 45) * 0.01)

dataset_new = list()
for i in range(10000):
  dataset_new.append(random.choice(dataset))

for i in range(5):
  print(random.choice(noise_dataset))
for i in range(5):
  print(random.choice(dataset_new))

([-0.1, 0.26], 0)
([0.22, 0.4], 0)
([0.02, 1.38], 1)
([0.01, 0.22], 0)
([0.42, -0.18], 0)
([1, 0], 1)
([1, 0], 1)
([0, 0], 0)
([0, 0], 0)
([0, 1], 1)


In [ ]:
# ф-ия активации
def result_bin_class(result):
  if (result > 0):
    return True
  else:
    return False

# ф-ия подсчета суммарного веса полученных сигналов
def calculate_res(input_number, first_layer_weights):
  sum = 0
  for i in range(2):
    sum += input_number[0][i] * first_layer_weights[i] # вычисление веса общего сигнала
  return sum

# ф-ия коррекции весов в зависимости от правильности ответа нейр. сети
def weight_changing(positive, target):
  k = 0
  if (positive and not target): # ошибка 1 рода
    k = -0.1
  elif (not positive and target): # ошибка 2 рода
    k = 0.1
  return k

# ф-ия для обучения нейронной сети
def learn(input_number, first_layer_weights, target):
  k = weight_changing(result_bin_class(calculate_res(input_number, first_layer_weights)), True if input_number[1] == target else False)
  for i in range(2):
    # меняем вклад от каждой ячейки
    first_layer_weights[i] += input_number[0][i] * k
  return first_layer_weights

# ф-ия обучения
def train_nn(input_dataset, first_layer_weights, target, size_of_data):
  for i in range(size_of_data):
    # обучаем на рандомных size_of_data значениях выборки input_dataset
    first_layer_weights = learn(random.choice(input_dataset), first_layer_weights, target)

In [ ]:
first_layer_weights = np.ones((2, 1))
train_nn(dataset_new, first_layer_weights, 1, 800)

In [ ]:
first_layer_weights

array([[1.],
       [1.]])

In [ ]:
# ф-ии для тестирования обученной нейронки
def test(input_number, first_layer_weights, target):
  if (result_bin_class(calculate_res(input_number, first_layer_weights)) == (True if input_number[1] == target else False)):
    return 1
  else:
    return 0

def test_nn(input_dataset, first_layer_weights, target, size_of_data):
  res = 0
  for i in range(size_of_data):
    res += test(random.choice(input_dataset), first_layer_weights, target) # как часто нейронка ошибается - введенная цифра == цели или нет
  return (res / size_of_data)

In [ ]:
print('Accuracy-score: ', test_nn(dataset, first_layer_weights, 1, 200))

Accuracy-score:  1.0


In [ ]:
first_layer_weights = np.ones((2, 1))
train_nn(noise_dataset, first_layer_weights, 1, 80)
print(first_layer_weights)
print('Accuracy-score: ', test_nn(noise_dataset, first_layer_weights, 1, 2000))

[[0.688]
 [0.757]]
Accuracy-score:  0.885


In [ ]:
train_nn(noise_dataset, first_layer_weights, 1, 800)
print(first_layer_weights)
print('Accuracy-score: ', test_nn(noise_dataset, first_layer_weights, 1, 200))

[[0.081]
 [0.067]]
Accuracy-score:  0.855
