<a href="https://colab.research.google.com/github/Ibilis37/DeepLearning/blob/main/ML_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Создание нейронной сети, выполняющей мультиклассовую классификацию

Создание модели (без использования готовых решений) перцептрона, которая будет определять к какому классу относится релультат операции {+, -}: {отрицательное число, ноль, положительное число}.

In [ ]:
import numpy as np
import random
import copy

In [ ]:
dataset = list()

actions = ['+','-']

for i in range(10000):
  temp = list()
  temp.append(random.randint(-100, 100) * 0.01)
  temp.append(random.randint(-100, 100) * 0.01)
  temp.append(random.randint(0, 1))
  if temp[2]: # '-'
    if temp[0] - temp[1] < 0:
      temp.append(0)
    elif temp[0] - temp[1] == 0:
      temp.append(1)
    else:
      temp.append(2)
  else: # '+'
    if temp[0] + temp[1] < 0:
      temp.append(0)
    elif temp[0] + temp[1] == 0:
      temp.append(1)
    else:
      temp.append(2)
  dataset.append(temp)


In [ ]:
random.choice(dataset)

[0.2, -1.0, 1, 2]

In [ ]:
first_layer_weight_multiclass = np.ones((3, 3))
print(first_layer_weight_multiclass)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
def calculate_res_multiclass(input_number, first_layer_weights):
  sum_array = list()
  for j in range(3):
    sum_array.append(0)
    for i in range(3):
      sum_array[j] += input_number[i] * first_layer_weights[i][j]
  return sum_array

def result_multiclass(sum_array):
  return sum_array.index(max(sum_array)) if max(sum_array) > 0 else 0

In [ ]:
def learn_multiclass(input_number, first_layer_weights):
  if (result_multiclass(calculate_res_multiclass(input_number, first_layer_weights)) != input_number[3]):
    for j in range(3):
      if j == input_number[3]:
        k = 0.5
      else:
        k = -0.1
      for i in range(3):
        first_layer_weights[i][j] += input_number[i] * k
  return first_layer_weights

In [ ]:
def train_nn_mc(input_dataset, first_layer_weights, size_of_dataset):
  for i in range(size_of_dataset):
    learn_multiclass(random.choice(input_dataset), first_layer_weights)

In [ ]:
train_nn_mc(dataset, first_layer_weight_multiclass, 80)

In [ ]:
def test_multiclass(input_number, first_layer_weights):
  if (result_multiclass(calculate_res_multiclass(input_number, first_layer_weights)) == input_number[3]):
    return 1
  else:
    return 0

In [ ]:
def test_nn_mc(input_dataset, first_layer_weights, size_of_dataset):
  res = 0
  for i in range(size_of_dataset):
    res += test_multiclass(random.choice(input_dataset), first_layer_weights)
  return (res / size_of_dataset)

In [ ]:
print('Accuracy-score: ', test_nn_mc(dataset, first_layer_weight_multiclass, 2000))

Accuracy-score:  0.818
